//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatieProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string Account1 { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public Nullable<int> Major { get; set; }
        public string Period { get; set; }
        public Nullable<int> TypeUser { get; set; }
        public Nullable<bool> IsMasterAdmin { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserUpdate { get; set; }
        public string Id { get; set; }
    
        public virtual MajorType MajorType { get; set; }
        public virtual TypeUser TypeUser1 { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
