//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatieProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> DateBorrow { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public Nullable<System.DateTime> LastDateToReturn { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
